name: "Validate the code coverage"
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: npm ci
      - name: "Lint"
        run: npm run lint
      - name: Coverage
        run: npm run coverage
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          fail_ci_if_error: true
